// FROM CAMERA
export const TAKE_PICTURE_REQUEST = 'TAKE_PICTURE_REQUEST';
export const TAKE_PICTURE_SUCCESS = 'TAKE_PICTURE_SUCCESS';
export const TAKE_PICTURE_ERROR = 'TAKE_PICTURE_ERROR';
export const TAKE_PICTURE_CANCELLED = 'TAKE_PICTURE_CANCELLED';

// FROM GALLERY
export const OPEN_GALLERY_REQUEST = 'OPEN_GALLERY_REQUEST';
export const OPEN_GALLERY_SUCCESS = 'OPEN_GALLERY_SUCCESS';
export const OPEN_GALLERY_ERROR = 'OPEN_GALLERY_ERROR';
export const OPEN_GALLERY_CANCELLED = 'OPEN_GALLERY_CANCELLED';

//IMAGES CONSTANTS
export const DELETE_IMAGE_REQUEST = 'REMOVE_IMAGE_REQUEST';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_FAILED = 'DELETE_IMAGE_FAILED';

//LOCATIONS CONSTANTS
export const ADD_LOCATIONS = 'ADD_LOCATIONS';
export const GET_LOCATIONS = 'GET_LOCATIONS';
